easy_admin:
    design:
       brand_color: '#1191d5'
    site_name: iBOOD Test
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i:s'
    design:
        assets:
            css: ['/bundles/app/css/custom_backend.css']
            js: ['/bundles/app/js/custom_backend.js']
    list:
        max_results: 30
        actions:
            - { name: 'new', icon: 'plus', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'remove', label: '' }
            - { name: 'show', icon: 'eye', label: '' }
