# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, ["@annotation_reader"]]

    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    twig_extension:
        class: AppBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }

    app.jms_serializer.media_preserialize_listener:
        class: AppBundle\Listener\MediaSerializerListener
        arguments: ['@router']
        tags:
            - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize }
